// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from './redux/provider';
import { Provider } from 'react-redux';
import { store } from './redux/store';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, Component, pageProps }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <Provider store={store}>
      <Component {...pageProps} />
          {children}
    </Provider>

        </Providers>
      </body>
    </html>
  );
}





// // app/layout.js
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { Provider } from 'react-redux';
// import { Providers } from './redux/provider';
// import { store } from './redux/store'; // Import your Redux store
// import Render from './render/page';

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//       <Providers>
//         {children}
//         </Providers>
//         </body>
//     </html>
//   );
// }
